services:
  default:
    build:
      args:
        - RENDERER_REPOSITORY=https://github.com/WoWs-Builder-Team/minimap_renderer.git
        - RENDERER_BRANCH=master
      context: .
    image: wows_minimap_renderer
  custom:
    build:
      args:
        - RENDERER_REPOSITORY=https://github.com/togashi/minimap_renderer.git
        - RENDERER_BRANCH=feature/assist-ribbons
      context: .
    image: wows_minimap_renderer:custom
